Fix lint issue
openshift/cluster-control-plane-machine-set-operator pull request #221
Opened 2023-06-22 14:46 UTC by EmilienM

2023-06-22 14:46 UTC, EmilienM commented
/assign @damdo

2023-06-22 15:25 UTC, EmilienM commented
/test unit

2023-06-22 15:48 UTC, damdo reviewed
Thanks, this was a leftover from my previous PR #180 
We should probably create a bug for this, so we can backport it back to 4.12, as linting might be failing there too.

2023-06-22 15:54 UTC, damdo commented
/retest OCPBUGS-15308: Fix lint issue

2023-06-22 15:54 UTC, damdo commented
/retitle OCPBUGS-15308: Fix lint issue

2023-06-22 15:55 UTC, damdo reviewed
/approve
/lgtm

2023-06-22 16:20 UTC, damdo requested changes
/remove-lgtm

2023-06-22 16:59 UTC, damdo commented
/retest

2023-06-22 19:14 UTC, damdo reviewed
/lgtm

2023-06-22 19:18 UTC, EmilienM commented
/skip
I wonder if we can save some trees by skipping the e2e jobs, not needed in this PR I think.

2023-06-22 22:01 UTC, damdo commented
/approve

2023-06-23 00:43 UTC, merged

2023-06-23 08:33 UTC, damdo commented
/cherry-pick release-4.13

2023-06-23 10:09 UTC, damdo commented
@miyadav you can see the lint job run passing [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-control-plane-machine-set-operator/221/pull-ci-openshift-cluster-control-plane-machine-set-operator-main-lint/1671943808708775936)